language: java
install: mvn install -DskipTests=true
script: mvn test integration-test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
# (Temporarily?) Remove build on jdk6 due to an incompatibility with the download-maven-plugin
#  - openjdk6

after_success:
  - mvn clean test integration-test jacoco:report
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - "chat.freenode.net#jlato"
    use_notice: true
    skip_join: true
    template:
      - "\x0313%{repository_name}\x03/\x036%{branch}\x03 \x0314%{commit}\x03 \x0315%{author}\x03: \x02#%{build_number} %{message}\x02"
      - "\x0315Build details:\x03 \x1F\x032%{build_url}\x03\x1F"

# http://lint.travis-ci.org/ validator
